nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmRegistryServer: "https://nexus.p42.at/repository/npm-midnight-ntwrk"
    npmAuthToken: # Add auth token here

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
